services:
    photon:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PHOTON_VERSION=${PHOTON_VERSION}
        environment:
            - IMPORT_MODE=jsonl
            - REGION=hu
            - LANGUAGES=hu,en
            - UPDATE_STRATEGY=DISABLED
            # - LOG_LEVEL=DEBUG
            # - FORCE_UPDATE=TRUE
        volumes:
            - photon_data:/photon/data
        restart: unless-stopped
        ports:
            - "2322:2322"
volumes:
    photon_data:
