services:
    photon:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PHOTON_VERSION=1.3.0
        container_name: "photon-docker"
        environment:
            - IMPORT_MODE=jsonl
            - REGION=hu
            - LANGUAGES=hu,en
            - UPDATE_STRATEGY=DISABLED
            - LOG_LEVEL=INFO # Options: DEBUG, INFO, ERROR
        volumes:
            - photon_data:/photon/data
        restart: unless-stopped
        ports:
            - "2322:2322"
volumes:
    photon_data:
